import type { Question } from "./jbti-types";

export const questions: Question[] = [
  { id: "q01", text: "参加一场只有少数熟人的聚会后，我通常比之前更有精神。", dimension: "social", direction: 1, weight: 1 },
  { id: "q02", text: "面对一周的任务，我会先排好大致顺序再开始。", dimension: "pace", direction: 1, weight: 1 },
  { id: "q03", text: "学习新工具时，我更愿意先照着实例操作。", dimension: "perception", direction: 1, weight: 1 },
  { id: "q04", text: "讨论分歧时，我首先想弄清论据是否站得住脚。", dimension: "decision", direction: 1, weight: 1 },
  { id: "q05", text: "连续与人相处几小时后，我会想独自安静一会儿。", dimension: "social", direction: -1, weight: 1 },
  { id: "q06", text: "临时改变计划常让我觉得事情更有活力。", dimension: "pace", direction: -1, weight: 1 },
  { id: "q07", text: "一个点子即使暂时没有现实用途，也会吸引我继续想象。", dimension: "perception", direction: -1, weight: 1 },
  { id: "q08", text: "做决定前，我会优先考虑它会让相关的人感受如何。", dimension: "decision", direction: -1, weight: 1 },
  { id: "q09", text: "有新话题时，我常通过说出来逐渐理清想法。", dimension: "social", direction: 1, weight: 1 },
  { id: "q10", text: "出门旅行前，我倾向于确定交通和关键安排。", dimension: "pace", direction: 1, weight: 1 },
  { id: "q11", text: "别人解释事情时，具体例子比抽象比喻更能说服我。", dimension: "perception", direction: 1, weight: 1 },
  { id: "q12", text: "团队意见相左时，我愿意支持标准更一致的方案。", dimension: "decision", direction: 1, weight: 1 },
  { id: "q13", text: "在安静的独处时间里，我更容易恢复注意力。", dimension: "social", direction: -1, weight: 1 },
  { id: "q14", text: "有多个可选路径时，我愿意边做边决定下一步。", dimension: "pace", direction: -1, weight: 1 },
  { id: "q15", text: "我常从看似不相干的事物之间发现有趣联系。", dimension: "perception", direction: -1, weight: 1 },
  { id: "q16", text: "即使方案效率更高，我也会在意它是否照顾到个体处境。", dimension: "decision", direction: -1, weight: 1 },
  { id: "q17", text: "进入新团队时，我通常会主动找人开启交流。", dimension: "social", direction: 1, weight: 1 },
  { id: "q18", text: "我喜欢把模糊目标拆成可以完成的小步骤。", dimension: "pace", direction: 1, weight: 1 },
  { id: "q19", text: "判断信息可靠性时，我会先找可以核对的事实。", dimension: "perception", direction: 1, weight: 1 },
  { id: "q20", text: "给朋友建议时，我会直接指出问题的关键矛盾。", dimension: "decision", direction: 1, weight: 1 },
  { id: "q21", text: "周末没有社交安排时，我通常不会觉得少了什么。", dimension: "social", direction: -1, weight: 1 },
  { id: "q22", text: "我更喜欢保留空白时间，让当天的状态决定安排。", dimension: "pace", direction: -1, weight: 1 },
  { id: "q23", text: "面对熟悉流程，我会自然想到还能有哪些新做法。", dimension: "perception", direction: -1, weight: 1 },
  { id: "q24", text: "别人来倾诉时，我通常先让对方感到被理解。", dimension: "decision", direction: -1, weight: 1 },
  { id: "q25", text: "需要完成复杂任务时，与人讨论能帮助我保持投入。", dimension: "social", direction: 1, weight: 1 },
  { id: "q26", text: "接近截止时间前，我倾向于让主要工作已经成形。", dimension: "pace", direction: 1, weight: 1 },
  { id: "q27", text: "选择方案时，我更信任曾经被验证过的方法。", dimension: "perception", direction: 1, weight: 1 },
  { id: "q28", text: "当规则适用于所有人时，我更容易接受它带来的不便。", dimension: "decision", direction: 1, weight: 1 },
  { id: "q29", text: "在人多嘈杂的活动中，我的精力通常下降得很快。", dimension: "social", direction: -1, weight: 1 },
  { id: "q30", text: "我可以在没有完整计划的情况下轻松开始一个项目。", dimension: "pace", direction: -1, weight: 1 },
  { id: "q31", text: "阅读故事时，隐藏的象征和多种解释常吸引我。", dimension: "perception", direction: -1, weight: 1 },
  { id: "q32", text: "如果一句话可能伤人，我会调整表达，即使它不够直接。", dimension: "decision", direction: -1, weight: 1 },
  { id: "q33", text: "得到好消息时，我很快会想找人分享。", dimension: "social", direction: 1, weight: 1 },
  { id: "q34", text: "使用清单会让我更安心，而不是觉得被束缚。", dimension: "pace", direction: 1, weight: 1 },
  { id: "q35", text: "做复盘时，我会关注具体发生了什么以及哪些步骤有效。", dimension: "perception", direction: 1, weight: 1 },
  { id: "q36", text: "评价一个方案时，我会尽量把个人好恶与标准分开。", dimension: "decision", direction: 1, weight: 1 },
  { id: "q37", text: "需要认真思考时，我更愿意先独自整理，再参与讨论。", dimension: "social", direction: -1, weight: 1 },
  { id: "q38", text: "当机会突然出现时，我愿意为它重排原有安排。", dimension: "pace", direction: -1, weight: 1 },
  { id: "q39", text: "比起掌握现状，我更容易被未来可能出现的变化吸引。", dimension: "perception", direction: -1, weight: 1 },
  { id: "q40", text: "冲突中即使我认为自己有理，也会先确认关系是否受到影响。", dimension: "decision", direction: -1, weight: 1 },
];

export const answerOptions = [
  { value: 1 as const, label: "很不像我", short: "1" },
  { value: 2 as const, label: "比较不像", short: "2" },
  { value: 3 as const, label: "不确定", short: "3" },
  { value: 4 as const, label: "比较像我", short: "4" },
  { value: 5 as const, label: "很像我", short: "5" },
];
